clean-md-start: "# Introduction"
sec-ref-style: section-sign-number  # number | number-title | section-sign-number
track-examples: false               # set true once example LUTs are populated

citation-sources:
- introduction-03-normative-references.md
- introduction-04-informative-references.md

glossary-sources:
- introduction-02-terminology-glossary.md

citation-skip-prefixes:
- '#'
